export const GET_ALL_STUDENTS_REQUEST = 'GET_ALL_STUDENTS_REQUEST';
export const GET_ALL_STUDENTS_SUCCESS = 'GET_ALL_STUDENTS_SUCCESS';
export const GET_ALL_STUDENTS_FAIL = 'GET_ALL_STUDENTS_FAIL';

export const GET_ALL_TEACHERS_REQUEST = 'GET_ALL_TEACHERS_REQUEST';
export const GET_ALL_TEACHERS_SUCCESS = 'GET_ALL_TEACHERS_SUCCESS';
export const GET_ALL_TEACHERS_FAIL = 'GET_ALL_TEACHERS_FAIL';

export const GET_ALL_CLASSROOMS_REQUEST = 'GET_ALL_CLASSROOMS_REQUEST';
export const GET_ALL_CLASSROOMS_SUCCESS = 'GET_ALL_CLASSROOMS_SUCCESS';
export const GET_ALL_CLASSROOMS_FAIL = 'GET_ALL_CLASSROOMS_FAIL';

export const ADD_CLASSROOM_REQUEST = 'ADD_CLASSROOM_REQUEST';
export const ADD_CLASSROOM_SUCCESS = 'ADD_CLASSROOM_SUCCESS';
export const ADD_CLASSROOM_FAIL = 'ADD_CLASSROOM_FAIL';
