export const setMobileView = 'setMobileView';


export const GET_ALL_STUDENTS_REQUEST = 'GET_ALL_STUDENTS_REQUEST';
export const GET_ALL_STUDENTS_SUCCESS = 'GET_ALL_STUDENTS_SUCCESS';
export const GET_ALL_STUDENTS_FAIL = 'GET_ALL_STUDENTS_FAIL';


export const GET_ALL_TEACHERS_REQUEST = 'GET_ALL_TEACHERS_REQUEST';
export const GET_ALL_TEACHERS_SUCCESS = 'GET_ALL_TEACHERS_SUCCESS';
export const GET_ALL_TEACHERS_FAIL = 'GET_ALL_TEACHERS_FAIL';


export const GET_ALL_COURSES_REQUEST = 'GET_ALL_COURSES_REQUEST';
export const GET_ALL_COURSES_SUCCESS = 'GET_ALL_COURSES_SUCCESS';
export const GET_ALL_COURSES_FAIL = 'GET_ALL_COURSES_FAIL';


export const GET_ALL_LECTURES_REQUEST = 'GET_ALL_LECTURES_REQUEST';
export const GET_ALL_LECTURES_SUCCESS = 'GET_ALL_LECTURES_SUCCESS';
export const GET_ALL_LECTURES_FAIL = 'GET_ALL_LECTURES_FAIL';

