export const GET_ALL_STUDENTS_REQUEST = 'GET_ALL_STUDENTS_REQUEST';
export const GET_ALL_STUDENTS_SUCCESS = 'GET_ALL_STUDENTS_SUCCESS';
export const GET_ALL_STUDENTS_FAIL = 'GET_ALL_STUDENTS_FAIL';


export const GET_ALL_CLASSROOMS_REQUEST = 'GET_ALL_CLASSROOMS_REQUEST';
export const GET_ALL_CLASSROOMS_SUCCESS = 'GET_ALL_CLASSROOMS_SUCCESS';
export const GET_ALL_CLASSROOMS_FAIL = 'GET_ALL_CLASSROOMS_FAIL';

export const ADD_CLASSROOM_REQUEST = 'ADD_CLASSROOM_REQUEST';
export const ADD_CLASSROOM_SUCCESS = 'ADD_CLASSROOM_SUCCESS';
export const ADD_CLASSROOM_FAIL = 'ADD_CLASSROOM_FAIL';

export const GET_EDIT_CLASSROOM_SUCCESS = 'GET_EDIT_CLASSROOM_SUCCESS';
export const GET_EDIT_CLASSROOM_FAIL = 'GET_EDIT_CLASSROOM_FAIL';

export const EDIT_CLASSROOM_REQUEST = 'EDIT_CLASSROOM_REQUEST';
export const EDIT_CLASSROOM_SUCCESS = 'EDIT_CLASSROOM_SUCCESS';
export const EDIT_CLASSROOM_FAIL = 'EDIT_CLASSROOM_FAIL';

export const DELETE_CLASSROOM_REQUEST = 'DELETE_CLASSROOM_REQUEST';
export const DELETE_CLASSROOM_SUCCESS = 'DELETE_CLASSROOM_SUCCESS';
export const DELETE_CLASSROOM_FAIL = 'DELETE_CLASSROOM_FAIL';

export const ADD_STUDENT_REQUEST = 'ADD_STUDENT_REQUEST';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_FAIL = 'ADD_STUDENT_FAIL'; 

export const GET_EDIT_STUDENT_SUCCESS = 'GET_EDIT_STUDENT_SUCCESS';
export const GET_EDIT_STUDENT_FAIL = 'GET_EDIT_STUDENT_FAIL';

export const EDIT_STUDENT_REQUEST = 'EDIT_STUDENT_REQUEST';
export const EDIT_STUDENT_SUCCESS = 'EDIT_STUDENT_SUCCESS';
export const EDIT_STUDENT_FAIL = 'EDIT_STUDENT_FAIL';

export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL';

// *****************TEACHERS*****************

export const GET_ALL_TEACHERS_REQUEST = 'GET_ALL_TEACHERS_REQUEST';
export const GET_ALL_TEACHERS_SUCCESS = 'GET_ALL_TEACHERS_SUCCESS';
export const GET_ALL_TEACHERS_FAIL = 'GET_ALL_TEACHERS_FAIL';

export const ADD_TEACHER_REQUEST = 'ADD_TEACHER_REQUEST';
export const ADD_TEACHER_SUCCESS = 'ADD_TEACHER_SUCCESS';
export const ADD_TEACHER_FAIL = 'ADD_TEACHER_FAIL';

export const GET_EDIT_TEACHER_SUCCESS = 'GET_EDIT_TEACHER_SUCCESS';
export const GET_EDIT_TEACHER_FAIL = 'GET_EDIT_TEACHER_FAIL';

export const EDIT_TEACHER_REQUEST = 'EDIT_TEACHER_REQUEST';
export const EDIT_TEACHER_SUCCESS = 'EDIT_TEACHER_SUCCESS';
export const EDIT_TEACHER_FAIL = 'EDIT_TEACHER_FAIL';

export const DELETE_TEACHER_REQUEST = 'DELETE_TEACHER_REQUEST';
export const DELETE_TEACHER_SUCCESS = 'DELETE_TEACHER_SUCCESS';
export const DELETE_TEACHER_FAIL = 'DELETE_TEACHER_FAIL';

// *****************LECTURES*****************
export const ADD_LECTURE_REQUEST = 'ADD_LECTURE_REQUEST';
export const ADD_LECTURE_SUCCESS = 'ADD_LECTURE_SUCCESS';
export const ADD_LECTURE_FAIL = 'ADD_LECTURE_FAIL';

export const GET_ALL_LECTURES_REQUEST = 'GET_ALL_LECTURES_REQUEST';
export const GET_ALL_LECTURES_SUCCESS = 'GET_ALL_LECTURES_SUCCESS';
export const GET_ALL_LECTURES_FAIL = 'GET_ALL_LECTURES_FAIL';

export const EDIT_LECTURE_REQUEST = 'EDIT_LECTURE_REQUEST';
export const EDIT_LECTURE_SUCCESS = 'EDIT_LECTURE_SUCCESS';
export const EDIT_LECTURE_FAIL = 'EDIT_LECTURE_FAIL';

export const DELETE_LECTURE_REQUEST = 'DELETE_LECTURE_REQUEST';
export const DELETE_LECTURE_SUCCESS = 'DELETE_LECTURE_SUCCESS';
export const DELETE_LECTURE_FAIL = 'DELETE_LECTURE_FAIL';


// *****************ADMIN*****************
export const GET_ALL_ADMINS_REQUEST = 'GET_ALL_ADMINS_REQUEST';
export const GET_ALL_ADMINS_SUCCESS = 'GET_ALL_ADMINS_SUCCESS';
export const GET_ALL_ADMINS_FAIL = 'GET_ALL_ADMINS_FAIL';

export const ADD_ADMIN_REQUEST = 'ADD_ADMIN_REQUEST';
export const ADD_ADMIN_SUCCESS = 'ADD_ADMIN_SUCCESS';
export const ADD_ADMIN_FAIL = 'ADD_ADMIN_FAIL';

export const GET_EDIT_ADMIN_SUCCESS = 'GET_EDIT_ADMIN_SUCCESS';
export const GET_EDIT_ADMIN_FAIL = 'GET_EDIT_ADMIN_FAIL';

export const EDIT_ADMIN_REQUEST = 'EDIT_ADMIN_REQUEST';
export const EDIT_ADMIN_SUCCESS = 'EDIT_ADMIN_SUCCESS';
export const EDIT_ADMIN_FAIL = 'EDIT_ADMIN_FAIL';

export const DELETE_ADMIN_REQUEST = 'DELETE_ADMIN_REQUEST';
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS';
export const DELETE_ADMIN_FAIL = 'DELETE_ADMIN_FAIL';

// *****************STUDENT_COURSES*****************
export const GET_ALL_STUDENT_COURSES_REQUEST = 'GET_ALL_STUDENT_COURSES_REQUEST';
export const GET_ALL_STUDENT_COURSES_SUCCESS = 'GET_ALL_STUDENT_COURSES_SUCCESS';
export const GET_ALL_STUDENT_COURSES_FAIL = 'GET_ALL_STUDENT_COURSES_FAIL';

// *****************MEET_LINKS*****************
export const GET_ALL_MEET_LINKS_REQUEST = 'GET_ALL_MEET_LINKS_REQUEST';
export const GET_ALL_MEET_LINKS_SUCCESS = 'GET_ALL_MEET_LINKS_SUCCESS';
export const GET_ALL_MEET_LINKS_FAIL = 'GET_ALL_MEET_LINKS_FAIL';

export const ADD_MEET_LINK_REQUEST = 'ADD_MEET_LINK_REQUEST';
export const ADD_MEET_LINK_SUCCESS = 'ADD_MEET_LINK_SUCCESS';
export const ADD_MEET_LINK_FAIL = 'ADD_MEET_LINK_FAIL';

export const EDIT_MEET_LINK_REQUEST = 'EDIT_MEET_LINK_REQUEST';
export const EDIT_MEET_LINK_SUCCESS = 'EDIT_MEET_LINK_SUCCESS';
export const EDIT_MEET_LINK_FAIL = 'EDIT_MEET_LINK_FAIL';

export const DELETE_MEET_LINK_REQUEST = 'DELETE_MEET_LINK_REQUEST';
export const DELETE_MEET_LINK_SUCCESS = 'DELETE_MEET_LINK_SUCCESS';
export const DELETE_MEET_LINK_FAIL = 'DELETE_MEET_LINK_FAIL';

export const GET_ALL_COURSES_REQUEST = 'GET_ALL_COURSES_REQUEST';
export const GET_ALL_COURSES_SUCCESS = 'GET_ALL_COURSES_SUCCESS';
export const GET_ALL_COURSES_FAIL = 'GET_ALL_COURSES_FAIL';
