export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const STUDENT_FAKE_AUTH = 'STUDENT_FAKE_AUTH'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const POST_NOTE_REQUEST = 'POST_NOTE_REQUEST'
export const POST_NOTE_SUCCESS = 'POST_NOTE_SUCCESS'
export const POST_NOTE_FAIL = 'POST_NOTE_FAIL'

export const DELETE_NOTE_REQUEST = 'DELETE_NOTE_REQUEST'
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS'
export const DELETE_NOTE_FAIL = 'DELETE_NOTE_FAIL'

export const GET_ALL_NOTES_REQUEST = 'GET_ALL_NOTES_REQUEST'
export const GET_ALL_NOTES_SUCCESS = 'GET_ALL_NOTES_SUCCESS'
export const GET_ALL_NOTES_FAIL = 'GET_ALL_NOTES_FAIL'


export const GET_ALL_COURSES_REQUEST = 'GET_ALL_COURSES_REQUEST'
export const GET_ALL_COURSES_SUCCESS = 'GET_ALL_COURSES_SUCCESS'
export const GET_ALL_COURSES_FAIL = 'GET_ALL_COURSES_FAIL'

export const COURSE_DETAIL_REQUEST = 'COURSE_DETAIL_REQUEST'
export const COURSE_DETAIL_SUCCESS = 'COURSE_DETAIL_SUCCESS'
export const COURSE_DETAIL_FAIL = 'COURSE_DETAIL_FAIL'

export const GET_ALL_ASSIGNMENT_REQUEST = 'GET_ALL_ASSIGNMENT_REQUEST';
export const GET_ALL_ASSIGNMENT_SUCCESS = 'GET_ALL_ASSIGNMENT_SUCCESS';
export const GET_ALL_ASSIGNMENT_FAIL = 'GET_ALL_ASSIGNMENT_FAIL';

export const POST_ASSIGNMENT_REQUEST = 'POST_ASSIGNMENT_REQUEST';
export const POST_ASSIGNMENT_SUCCESS = 'POST_ASSIGNMENT_SUCCESS';
export const POST_ASSIGNMENT_FAIL = 'POST_ASSIGNMENT_FAIL';

export const UPDATE_ASSIGNMENT_REQUEST = 'UPDATE_ASSIGNMENT_REQUEST';
export const UPDATE_ASSIGNMENT_SUCCESS = 'UPDATE_ASSIGNMENT_SUCCESS';
export const UPDATE_ASSIGNMENT_FAIL = 'UPDATE_ASSIGNMENT_FAIL';

export const DELETE_ASSIGNMENT_REQUEST = 'DELETE_ASSIGNMENT_REQUEST';
export const DELETE_ASSIGNMENT_SUCCESS = 'DELETE_ASSIGNMENT_SUCCESS';
export const DELETE_ASSIGNMENT_FAIL = 'DELETE_ASSIGNMENT_FAIL';

export const POST_COURSE_ACTIVITY_REQUEST = 'POST_COURSE_ACTIVITY_REQUEST';
export const POST_COURSE_ACTIVITY_SUCCESS = 'POST_COURSE_ACTIVITY_SUCCESS';
export const POST_COURSE_ACTIVITY_FAIL = 'POST_COURSE_ACTIVITY_FAIL';


export const POST_NEW_QUIZ_REQUEST = 'POST_NEW_QUIZ_REQUEST'
export const POST_NEW_QUIZ_SUCCESS = 'POST_NEW_QUIZ_SUCCESS'
export const POST_NEW_QUIZ_FAIL = 'POST_NEW_QUIZ_FAIL'

export const DELETE_QUIZ_REQUEST = 'DELETE_QUIZ_REQUEST'
export const DELETE_QUIZ_SUCCESS = 'DELETE_QUIZ_SUCCESS'
export const DELETE_QUIZ_FAIL = 'DELETE_QUIZ_FAIL'

export const POST_QUIZ_QUESTION_REQUEST = 'POST_QUIZ_QUESTION_REQUEST'
export const POST_QUIZ_QUESTION_SUCCESS = 'POST_QUIZ_QUESTION_SUCCESS'
export const POST_QUIZ_QUESTION_FAIL = 'POST_QUIZ_QUESTION_FAIL'

export const DELETE_QUIZ_QUESTION_REQUEST = 'DELETE_QUIZ_QUESTION_REQUEST'
export const DELETE_QUIZ_QUESTION_SUCCESS = 'DELETE_QUIZ_QUESTION_SUCCESS'
export const DELETE_QUIZ_QUESTION_FAIL = 'DELETE_QUIZ_QUESTION_FAIL'

export const UPDATE_QUIZ_QUESTION_REQUEST = 'UPDATE_QUIZ_QUESTION_REQUEST'
export const UPDATE_QUIZ_QUESTION_SUCCESS = 'UPDATE_QUIZ_QUESTION_SUCCESS'
export const UPDATE_QUIZ_QUESTION_FAIL = 'UPDATE_QUIZ_QUESTION_FAIL'

export const GET_ALL_LECTURE_REQUEST = 'GET_ALL_LECTURE_REQUEST'
export const GET_ALL_LECTURE_SUCCESS = 'GET_ALL_LECTURE_SUCCESS'
export const GET_ALL_LECTURE_FAIL = 'GET_ALL_LECTURE_FAIL'

// export const GET_CLASSROOM_BY_ID_REQUEST = 'GET_CLASSROOM_BY_ID_REQUEST'
// export const GET_CLASSROOM_BY_ID_REQUEST = 'GET_CLASSROOM_BY_ID_REQUEST'
// export const GET_CLASSROOM_BY_ID_REQUEST = 'GET_CLASSROOM_BY_ID_REQUEST'
